### ISSUE TITLE
Use cookies for web dashboard and fix redirect bug

### ISSUE THREAD

**Issue by VenkSociety** [VenkSociety/Tsuyo#26]
`Error: listen EADDRINUSE: address already in use :::3000
at Server.setupListenHandle [as _listen2] (net.js:1308:16)
at listenInCluster (net.js:1356:12)
at Server.listen (net.js:1444:7)
at Function.listen (/root/Tsuyo-latest/Tsuyo/node_modules/express/lib/application.js:618:24)
at initWeb (/root/Tsuyo-latest/Tsuyo/modules/web.js:62:7)
at module.exports (/root/Tsuyo-latest/Tsuyo/events/ready.js:41:28)
at Client.emit (events.js:317:22)
at WebSocketConnection.triggerReady (/root/Tsuyo-latest/Tsuyo/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:128:17)
at WebSocketConnection.checkIfReady (/root/Tsuyo-latest/Tsuyo/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:144:61)
at ReadyHandler.handle (/root/Tsuyo-latest/Tsuyo/node_modules/discord.js/src/client/websocket/packets/handlers/Ready.js:80:8)`

**Comment by felixfong227** [comment]
Currently, I am looking for an SQLite solution for storing and managing cookies, but so far no luck 😭 

Having troubles using the actual plugins

Packages I tried:

* `connect-session-sequelize`
* `express-session-sqlite`

Using `express-session-sqlite`:

Manage to set up everything, no error what so ever, but the cookie ever get stored in the local machine, it literally did nothing 🤔 

Using `connect-session-sequelize`:

The SQLite file get store in the local machine, but none of the requires tables are ever get created thus throwing a bunch of error saying that missing table `Session`

**Comment by VenkSociety** [comment]
I've been told [this](http://prntscr.com/tp1u2d) works @felixfong227 if you're down to try that. I'm certainly no expert when it comes to networking and sessions however.
