### ISSUE TITLE
guilds.forEach is not a function error

### ISSUE THREAD

**Issue by coolman4** [VenkSociety/Tsuyo#31]
I get this error when I'm on the dashboard.

Error: 
```TypeError: /home/runner/Tsuyo-1/views/servers.ejs:11
    9|       <div class="servers">
    10| 		  <h1 class="title">Servers you can manage:</h1>
 >> 11| 		  <% guilds.forEach((guild) => { %>
    12| 			<% if (!djsclient.guilds.has(guild.id)) { %>
    13| 			  <a id="invite-btn" target="_blank" href="https://discordapp.com/oauth2/authorize?client_id=492871769485475840&scope=bot&permissions=1506142455&guild_id=<%= guild.id %>">Invite to server
    14| 			  </a>

guilds.forEach is not a function
    at eval (/home/runner/Tsuyo-1/views/servers.ejs:15:15)
    at servers (/home/runner/Tsuyo-1/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (/home/runner/Tsuyo-1/node_modules/ejs/lib/ejs.js:254:36)
    at View.exports.renderFile [as engine] (/home/runner/Tsuyo-1/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/home/runner/Tsuyo-1/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/runner/Tsuyo-1/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/runner/Tsuyo-1/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/runner/Tsuyo-1/node_modules/express/lib/response.js:1012:7)
    at router.get (/home/runner/Tsuyo-1/routes/servers.js:7:7)
    at Layer.handle [as handle_request] (/home/runner/Tsuyo-1/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by VenkSociety** [comment]
Does this error show in console automatically or is there a way to replicate it? Also, if possible, which Discord.js version are you running?

**Comment by coolman4** [comment]
it shows on console when I go to the website servers page.

**Comment by coolman4** [comment]
I use repl.it can that be a problem?

**Comment by VenkSociety** [comment]
Are you using Discord.JS v11? v12 is unstable atm.

As for repl.it, I'm not familiar with it alas. Try running locally via NPM/NodeJS and see if the error still occurs. It's weird that one aspect of the dashboard doesn't work while the rest does hm...

**Comment by coolman4** [comment]
with dashboard disabled no error, And I can't run it off my computer because I have chromebook.

**Comment by coolman4** [comment]
I'm using 12, I can't get 11. Repl.it gets the latest update of the packages automaticly

**Comment by 0x00032** [comment]
This error is because you need to add djsclient.guilds.forEach istead of guilds.forEach

**Comment by coolman4** [comment]
I'll try it

**Comment by coolman4** [comment]
It fixed the http://spark.unobot.ga/servers error now there is another error when I go to manage the server.
`TypeError: Cannot read property 'hasPermission' of undefined
    at router.get (/home/runner/Tsuyo-1/routes/server.js:18:71)
    at Layer.handle [as handle_request] (/home/runner/Tsuyo-1/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/Tsuyo-1/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/runner/Tsuyo-1/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/runner/Tsuyo-1/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/Tsuyo-1/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/runner/Tsuyo-1/node_modules/express/lib/router/index.js:335:12)
    at next (/home/runner/Tsuyo-1/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/runner/Tsuyo-1/node_modules/express/lib/router/index.js:174:3)
    at router (/home/runner/Tsuyo-1/node_modules/express/lib/router/index.js:47:12)
`

**Comment by coolman4** [comment]
with the new bot update I still get the error
