### ISSUE TITLE
got error log selfhost TOKEN

### ISSUE THREAD

**Issue by kasepta** [VenkSociety/Tsuyo#62]
i have to add my token bot
```Logged into Discord API!
[Tsuyo] ✘ ERR:   Error [TOKEN_INVALID]: An invalid token was provided.
Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\Users\Kasepta\Desktop\Tsuyo-master\node_modules\discord.js\src\client\Client.js:205:52)
    at Object.<anonymous> (C:\Users\Kasepta\Desktop\Tsuyo-master\bot.js:76:8)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[Tsuyo] → INFO:  Loading command: 50. Command 1
[Tsuyo] ✘ ERR:   C:\Users\Kasepta\Desktop\Tsuyo-master\commands\8ball.js:30
  }
  ^

SyntaxError: Missing catch or finally after try
    at wrapSafe (internal/modules/cjs/loader.js:992:16)
    at Module._compile (internal/modules/cjs/loader.js:1040:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\Users\Kasepta\Desktop\Tsuyo-master\modules\commands.js:23:19
    at Array.forEach (<anonymous>)
    at C:\Users\Kasepta\Desktop\Tsuyo-master\modules\commands.js:18:11
```

**Comment by cluzier** [comment]
I am getting this error too

**Comment by VenkSociety** [comment]
Not sure what the problem is exactly, it follows the same syntax as we've always used and never had any issues. Even putting the token in quotations didn't seem to fix the problem.

I don't think it's a _Tsuyo_ problem directly, but instead that of either the `Discord.js` or `dotenv` NPM modules. If you have any idea on how to fix this, _or more so, why it is occuring_, please feel free to leave a comment or create a pull request.
